### PR TITLE
Added Cdn77.com to company list

### PR DESCRIPTION
**Pull request by xlilien**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
@xlilien Thanks!

**Comment by xlilien** [comment]
Hi @TomasVotruba , I noticed that adding the company cdn77.com in this PR was removed in this commit: https://github.com/Symfonisti/symfonycz.github.io/commit/3d005a96ca0ce57c7a999021bea0bd79e19d6806

Just wondering whether it was by mistake or on purpose. Thanks for an answer :-)

**Comment by TomasVotruba** [comment]
Hi @xlilien , oh, I'm sorry, that was not the intention :/. My bad.

Could you please resend the PR with adding it?

**Comment by xlilien** [comment]
Hi @TomasVotruba , no big deal, I have just done it. Thx :-)

**Pull request merged**
